export const UPLOAD_VIDEO_START = 'UPLOAD_VIDEO_START';
export const UPLOAD_VIDEO_FINISHED = 'UPLOAD_VIDEO_FINISHED';

export const GET_VIDEO_LIST_START = 'GET_VIDEO_LIST_START';
export const GET_VIDEO_LIST_FINISHED = 'GET_VIDEO_LIST_FINISHED';
